export { createSlotRegistry } from './slots'
export type { SlotName, SlotRegistry } from './slots'
export { createBridgeClient, RpcError, wsClientBridge } from './connection'
export type { ClientBridge, ClientTransport, WsClientOptions } from './connection'
export { createClientSessionStore } from './store'
export type { ClientSessionStore } from './store'
export { projectConversation, projectToolCards } from './projection'
export type { DisplayMessage, ToolCard } from './projection'
export { clientShell } from './shell'
export type { ClientShellConfig } from './shell'
export { ClientRoot, SlotContext, useSlotStore } from './react'
export { SessionListPanel, uiSessionList } from './ui/session-list'
export { ConversationPanel, uiConversation } from './ui/conversation'
export { ToolPanel, uiTool } from './ui/tool'
